<?php
add_action( 'wp_enqueue_scripts', 'theme_enqueue_styles' );
function theme_enqueue_styles() {
    wp_enqueue_style( 'parent-style', get_template_directory_uri() . '/style.css' );

     //Add custom CSS generated by SASS
        wp_enqueue_style( 'child-style',
        get_stylesheet_directory_uri() . '/assets/css/main.css',
        array( 'parent-style' ),
        wp_get_theme()->get('Version')
    );


    //Add custom JS
        wp_enqueue_script( 'child-js',
        get_stylesheet_directory_uri() . '/js/main.js',
        array( 'jquery' ),
        wp_get_theme()->get('Version'),
        true
    );
}

// Get customizer options form parent theme
if ( get_stylesheet() !== get_template() ) {
    add_filter( 'pre_update_option_theme_mods_' . get_stylesheet(), function ( $value, $old_value ) {
        update_option( 'theme_mods_' . get_template(), $value );
        return $old_value; // prevent update to child theme mods
    }, 10, 2 );
    add_filter( 'pre_option_theme_mods_' . get_stylesheet(), function ( $default ) {
        return get_option( 'theme_mods_' . get_template(), $default );
    } );
}

//---------- ETAPE 3 : importation script Swiper JS ------ //

function enqueue_swiper_assets() {
    // Enqueue Swiper CSS
    wp_enqueue_style('swiper-css', 'https://unpkg.com/swiper@9/swiper-bundle.min.css', array(), null);

    // Enqueue Swiper JS
    wp_enqueue_script('swiper-js', 'https://unpkg.com/swiper@9/swiper-bundle.min.js', array(), null, true);

    // Ajouter son propre code Swiper
    wp_enqueue_script('custom-swiper-init', get_stylesheet_directory_uri() . '/js/custom-swiper-init.js', array('swiper-js'), null, true);
}

add_action('wp_enqueue_scripts', 'enqueue_swiper_assets');
